// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';


export class ColumnIndexEntry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ColumnIndexEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsColumnIndexEntry(bb:flatbuffers.ByteBuffer, obj?:ColumnIndexEntry):ColumnIndexEntry {
  return (obj || new ColumnIndexEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsColumnIndexEntry(bb:flatbuffers.ByteBuffer, obj?:ColumnIndexEntry):ColumnIndexEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ColumnIndexEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

offset():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

length():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startColumnIndexEntry(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addOffset(builder:flatbuffers.Builder, offset:bigint) {
  builder.addFieldInt64(1, offset, BigInt('0'));
}

static addLength(builder:flatbuffers.Builder, length:bigint) {
  builder.addFieldInt64(2, length, BigInt('0'));
}

static endColumnIndexEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4); // name
  return offset;
}

static createColumnIndexEntry(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, offset:bigint, length:bigint):flatbuffers.Offset {
  ColumnIndexEntry.startColumnIndexEntry(builder);
  ColumnIndexEntry.addName(builder, nameOffset);
  ColumnIndexEntry.addOffset(builder, offset);
  ColumnIndexEntry.addLength(builder, length);
  return ColumnIndexEntry.endColumnIndexEntry(builder);
}
}
