import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { deserialize, FlatRecord } from '../../src/ts/geojson.js';

/**
 * Smoke tests that exercise the static FlatRecord fixtures generated by
 * `script/gen_fixtures.ts`. Their purpose is twofold:
 *
 *  1. Catch regressions where the on-disk binary format would change
 *     without anyone noticing (the fixtures are committed bytes, so
 *     any incompatible change to the writer breaks these tests).
 *  2. Document the canonical "small / medium / no-indices" datasets
 *     used elsewhere in the docs and tests.
 *
 * If the format intentionally changes, regenerate with
 * `npx tsx script/gen_fixtures.ts` and commit the new bytes.
 */

const DATA_DIR = resolve(__dirname, '..', 'data');
function readFixture(name: string): Uint8Array {
    return new Uint8Array(readFileSync(resolve(DATA_DIR, name)));
}

async function collect<T>(iter: AsyncIterable<T>): Promise<T[]> {
    const out: T[] = [];
    for await (const v of iter) out.push(v);
    return out;
}

describe('cities-network.frb fixture', () => {
    it('round-trips 5 capitals + 5 directed edges with default indices', async () => {
        const bytes = readFixture('cities-network.frb');
        const { features, adjacencyList } = await deserialize(bytes);

        expect(features).toHaveLength(5);
        const names = new Set(features.map((f) => (f.properties as { name: string }).name).sort());
        expect(names).toEqual(new Set(['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Curitiba']));

        expect(adjacencyList.links).toHaveLength(5);
        // Every edge carries the road/km properties from the fixture.
        for (const e of adjacencyList.links) {
            expect(typeof e.properties?.road).toBe('string');
            expect(typeof e.properties?.km).toBe('number');
        }
    });

    it('exposes all three indices via the metadata callback', async () => {
        const bytes = readFixture('cities-network.frb');
        let meta: import('../../src/ts/link-types.js').FlatRecordMeta | null = null;
        await deserialize(bytes, (m) => {
            meta = m;
        });
        const m = meta as unknown as import('../../src/ts/link-types.js').FlatRecordMeta;
        expect(m.indexNodeSize).toBe(16);
        expect(m.crs?.code).toBe(4326);
        expect((m.linkAdjacencyIndex.length > 0)).toBe(true);
        expect((m.linkSpatialIndex.length > 0)).toBe(true);
    });

    it('supports random-access queries via FlatRecord', async () => {
        const bytes = readFixture('cities-network.frb');
        const fr = await FlatRecord.open(bytes);

        // Outgoing edges of São Paulo (whatever its Hilbert-sorted index is).
        const { features } = await deserialize(bytes);
        const sp = features.findIndex((f) => (f.properties as { iata: string }).iata === 'SAO');
        expect(sp).toBeGreaterThanOrEqual(0);
        const out = await collect(fr.outgoingLinksOf(sp));
        expect(out.length).toBeGreaterThan(0);
        for (const e of out) {
            expect(e.from).toBe(sp);
        }
    });
});

describe('grid-with-paths.frb fixture', () => {
    it('round-trips a 4×4 grid with bidirectional edges + a curved diagonal', async () => {
        const bytes = readFixture('grid-with-paths.frb');
        const { features, adjacencyList } = await deserialize(bytes);

        expect(features).toHaveLength(16);
        // 4×4 grid → 24 lateral pairs × 2 (bidirectional) + 1 diagonal = 49
        expect(adjacencyList.links).toHaveLength(49);

        // Exactly one edge carries an explicit LineString geometry.
        const withGeom = adjacencyList.links.filter((e) => e.geometry !== null);
        expect(withGeom).toHaveLength(1);
        expect(withGeom[0].geometry?.type).toBe('LineString');
        expect(withGeom[0].geometry?.coordinates).toHaveLength(4);
    });

    it('shortestPath corner-to-corner respects the grid topology', async () => {
        const bytes = readFixture('grid-with-paths.frb');
        const fr = await FlatRecord.open(bytes);
        const { features } = await deserialize(bytes);
        const idxByOrigId = new Map(
            features.map((f, i) => [(f.properties as { id: number }).id, i] as const),
        );
        const fromIdx = idxByOrigId.get(0) as number;
        const toIdx = idxByOrigId.get(15) as number;

        // The fixture's explicit diagonal edge (0 → 15) is a single hop
        // and stays the cheapest option even though it follows a
        // dog-leg LineString.
        const path = await fr.shortestPath(fromIdx, toIdx);
        expect(path).not.toBeNull();
        if (!path) return;
        expect(path.links).toHaveLength(1);
        expect(path.links[0].geometry?.coordinates).toHaveLength(4);
    });

    it('featuresInBbox returns the vertices inside the requested rectangle', async () => {
        const bytes = readFixture('grid-with-paths.frb');
        const fr = await FlatRecord.open(bytes);
        // The fixture lays the grid at lon -46.6 → -46.57, lat -23.5 → -23.47.
        // Pick a small bbox in the south-west corner.
        const hits = await collect(
            fr.featuresInBbox({ minX: -46.601, minY: -23.501, maxX: -46.585, maxY: -23.485 }),
        );
        expect(hits.length).toBeGreaterThan(0);
        for (const h of hits) {
            const [x, y] = (h.geometry as { coordinates: [number, number] }).coordinates;
            expect(x).toBeGreaterThanOrEqual(-46.601);
            expect(x).toBeLessThanOrEqual(-46.585);
            expect(y).toBeGreaterThanOrEqual(-23.501);
            expect(y).toBeLessThanOrEqual(-23.485);
        }
    });
});

describe('no-indices.frb fixture', () => {
    it('round-trips features and edges in original order', async () => {
        const bytes = readFixture('no-indices.frb');
        const { features, adjacencyList } = await deserialize(bytes);
        expect(features).toHaveLength(3);
        expect(features.map((f) => (f.properties as { name: string }).name)).toEqual(['A', 'B', 'C']);
        expect(adjacencyList.links).toHaveLength(2);
        expect(adjacencyList.links[0].from).toBe(0);
        expect(adjacencyList.links[0].to).toBe(1);
        expect(adjacencyList.links[1].from).toBe(1);
        expect(adjacencyList.links[1].to).toBe(2);
    });

    it('exposes "no indices" via the metadata callback', async () => {
        const bytes = readFixture('no-indices.frb');
        let meta: import('../../src/ts/link-types.js').FlatRecordMeta | null = null;
        await deserialize(bytes, (m) => {
            meta = m;
        });
        const m = meta as unknown as import('../../src/ts/link-types.js').FlatRecordMeta;
        expect(m.indexNodeSize).toBe(0);
        expect((m.linkAdjacencyIndex.length > 0)).toBe(false);
        expect((m.linkSpatialIndex.length > 0)).toBe(false);
    });

    it('rejects index-dependent queries with descriptive errors', async () => {
        const bytes = readFixture('no-indices.frb');
        const fr = await FlatRecord.open(bytes);
        await expect(collect(fr.outgoingLinksOf(0))).rejects.toThrow(/writeAdjacencyIndex/);
        await expect(
            collect(fr.linksInBbox({ minX: -100, minY: -100, maxX: 100, maxY: 100 })),
        ).rejects.toThrow(/writeLinkSpatialIndex/);
        await expect(
            collect(fr.featuresInBbox({ minX: -100, minY: -100, maxX: 100, maxY: 100 })),
        ).rejects.toThrow(/writeSpatialIndex/);
        await expect(fr.shortestPath(0, 2)).rejects.toThrow(/writeAdjacencyIndex/);
    });
});

describe('table-users.frb fixture (table mode)', () => {
    it('is a `table` mode file (no geometry, no links)', async () => {
        const fr = await FlatRecord.open(readFixture('table-users.frb'));
        expect(fr.mode).toBe('table');
        expect(fr.hasGeometry).toBe(false);
        expect(fr.hasLinks).toBe(false);
        expect(fr.featuresCount).toBe(5);
        expect(fr.linksCount).toBe(0);
    });

    it('round-trips rows via deserialize', async () => {
        const result = await deserialize(readFixture('table-users.frb'));
        expect(result.mode).toBe('table');
        if (result.mode !== 'table' && result.mode !== 'graph') {
            throw new Error('expected tabular result');
        }
        expect(result.rows).toEqual([
            { id: 'u1', name: 'Alice', age: 30, vip: true },
            { id: 'u2', name: 'Bob', age: 25, vip: false },
            { id: 'u3', name: 'Carol', age: 45, vip: true },
            { id: 'u4', name: 'Dan', age: 18, vip: false },
            { id: 'u5', name: 'Erin', age: 60, vip: true },
        ]);
        expect(result.adjacencyList.links).toHaveLength(0);
    });

    it('exposes property indices on text / number / boolean columns', async () => {
        const fr = await FlatRecord.open(readFixture('table-users.frb'));

        const text = await collect(fr.findFeaturesByText('name', 'alice'));
        expect(text.map((h) => h.feature.properties.name)).toEqual(['Alice']);

        const seniors = await collect(fr.findFeaturesByValue('age', { gte: 45 }));
        expect(seniors.map((f) => f.properties.name).sort()).toEqual(['Carol', 'Erin']);

        const vips = await collect(fr.findFeaturesByValue('vip', { eq: true }));
        expect(vips).toHaveLength(3);
    });

    it('rejects geometry / link queries with descriptive errors', async () => {
        const fr = await FlatRecord.open(readFixture('table-users.frb'));
        await expect(
            collect(fr.featuresInBbox({ minX: 0, minY: 0, maxX: 1, maxY: 1 })),
        ).rejects.toThrow(/no geometry/i);
        await expect(collect(fr.outgoingLinksOf(0))).rejects.toThrow(/no links/i);
    });

    it('reports tabular metadata via callback', async () => {
        let meta: import('../../src/ts/link-types.js').FlatRecordMeta | null = null;
        await deserialize(readFixture('table-users.frb'), (m) => {
            meta = m;
        });
        const m = meta as unknown as import('../../src/ts/link-types.js').FlatRecordMeta;
        expect(m.mode).toBe('table');
        expect(m.hasGeometry).toBe(false);
        expect(m.hasLinks).toBe(false);
        expect(m.columns?.map((c) => c.name).sort()).toEqual(['age', 'id', 'name', 'vip']);
        expect(m.featureColumnIndices.length).toBe(4);
    });
});

describe('graph-deps.frb fixture (graph mode)', () => {
    it('is a `graph` mode file (no geometry, has links)', async () => {
        const fr = await FlatRecord.open(readFixture('graph-deps.frb'));
        expect(fr.mode).toBe('graph');
        expect(fr.hasGeometry).toBe(false);
        expect(fr.hasLinks).toBe(true);
        expect(fr.featuresCount).toBe(5);
        expect(fr.linksCount).toBe(7);
    });

    it('round-trips features (rows) + links via deserialize', async () => {
        const result = await deserialize(readFixture('graph-deps.frb'));
        expect(result.mode).toBe('graph');
        if (result.mode !== 'graph') throw new Error('expected graph mode');
        expect(result.rows).toEqual([
            { pkg: 'app', version: '1.0.0' },
            { pkg: 'auth', version: '2.3.1' },
            { pkg: 'db', version: '4.0.0' },
            { pkg: 'cache', version: '1.5.2' },
            { pkg: 'logger', version: '0.9.0' },
        ]);
        expect(result.adjacencyList.links).toHaveLength(7);
    });

    it('outgoingLinksOf works on the CSR', async () => {
        const fr = await FlatRecord.open(readFixture('graph-deps.frb'));
        const out = await collect(fr.outgoingLinksOf(0));
        expect(out.map((l) => l.to).sort()).toEqual([1, 2, 4]);
        const kinds = out.map((l) => l.properties.kind).sort();
        expect(kinds).toEqual(['dev', 'runtime', 'runtime']);
    });

    it('property index on links resolves text + boolean predicates', async () => {
        const fr = await FlatRecord.open(readFixture('graph-deps.frb'));

        const dev = await collect(fr.findLinksByText('kind', 'dev'));
        expect(dev).toHaveLength(1);

        const optional = await collect(fr.findLinksByValue('optional', { eq: true }));
        expect(optional).toHaveLength(2);
    });

    it('shortestPath traverses the dependency graph (custom weight)', async () => {
        const fr = await FlatRecord.open(readFixture('graph-deps.frb'));
        // Weight 1 per link → shortest path is hop count.
        const path = await fr.shortestPath(0, 3, { weight: () => 1 });
        expect(path).not.toBeNull();
        expect(path?.features.map((f) => f.properties.pkg)).toEqual(['app', 'db', 'cache']);
        expect(path?.cost).toBe(2);
    });

    it('lookup by `pkg` feeds straight into shortestPath', async () => {
        const fr = await FlatRecord.open(readFixture('graph-deps.frb'));
        const path = await fr.shortestPath(
            { column: 'pkg', value: 'app' },
            { column: 'pkg', value: 'logger' },
            { weight: () => 1 },
        );
        expect(path).not.toBeNull();
        expect(path?.features[0].properties.pkg).toBe('app');
        expect(path?.features[path.features.length - 1].properties.pkg).toBe('logger');
    });

    it('rejects geometry queries', async () => {
        const fr = await FlatRecord.open(readFixture('graph-deps.frb'));
        await expect(
            collect(fr.featuresInBbox({ minX: 0, minY: 0, maxX: 1, maxY: 1 })),
        ).rejects.toThrow(/no geometry/i);
    });
});

describe('text-search-large.frb fixture (text search performance)', () => {
    it('opens 5 000-row file in under 100 ms', async () => {
        const bytes = readFixture('text-search-large.frb');
        const t0 = performance.now();
        const fr = await FlatRecord.open(bytes);
        const ms = performance.now() - t0;
        expect(fr.featuresCount).toBe(5000);
        expect(fr.mode).toBe('table');
        expect(ms).toBeLessThan(100);
    });

    it('text search on a fat description column completes under 200 ms', async () => {
        const bytes = readFixture('text-search-large.frb');
        const fr = await FlatRecord.open(bytes);
        await fr.preload();   // warm caches once

        const queries = ['volcanic crater', 'maritime harbor', 'quantum observatory'];
        for (const q of queries) {
            const t0 = performance.now();
            const hits = await collect(fr.findFeaturesByText('description', q, { limit: 100 }));
            const ms = performance.now() - t0;
            // Limited to 100 results; tier-A hits come first.
            expect(hits.length).toBeGreaterThan(0);
            expect(hits.length).toBeLessThanOrEqual(100);
            expect(['A', 'B', 'C']).toContain(hits[0].tier);
            // Single text query on 5 k rows × ~20 tokens should be very fast.
            expect(ms).toBeLessThan(200);
        }
    });

    it('exact-token lookup on category resolves featureIndexBy correctly', async () => {
        const fr = await FlatRecord.open(readFixture('text-search-large.frb'));
        await fr.loadFeatureColumnIndex('id');
        const idx = await fr.featureIndexBy({ column: 'id', value: 'R02500' });
        expect(idx).toBe(2500);
    });

    it('numeric range on score returns expected count', async () => {
        const fr = await FlatRecord.open(readFixture('text-search-large.frb'));
        const high = await collect(fr.findFeaturesByValue('score', { gte: 900 }));
        // Scores are (i * 13) % 1000 for i in 0..4999. Roughly 10 % fall in [900, 1000).
        expect(high.length).toBeGreaterThan(400);
        expect(high.length).toBeLessThan(600);
    });

    it('loads only one column index when only one column is queried', async () => {
        const bytes = readFixture('text-search-large.frb');
        const fr = await FlatRecord.open(bytes);
        // Targeted single-column load: cheap on remote files because
        // each column index is its own block in the directory.
        const t0 = performance.now();
        const hits = await collect(
            fr.findFeaturesByText('description', 'arctic university', { limit: 10 }),
        );
        const ms = performance.now() - t0;
        expect(hits.length).toBeGreaterThan(0);
        // First call materialises just the `description` index block.
        expect(ms).toBeLessThan(500);
    });
});

describe('with-metadata.frb fixture (every header identity field set)', () => {
    it('reads `name` verbatim', async () => {
        const fr = await FlatRecord.open(readFixture('with-metadata.frb'));
        expect(fr.header.name).toBe('fixtures.metadata.demo');
    });

    it('reads `title` verbatim', async () => {
        const fr = await FlatRecord.open(readFixture('with-metadata.frb'));
        expect(fr.header.title).toBe('FlatRecord metadata fixture');
    });

    it('reads `description` verbatim (multi-sentence)', async () => {
        const fr = await FlatRecord.open(readFixture('with-metadata.frb'));
        expect(fr.header.description?.startsWith('A tiny tabular file')).toBe(true);
        expect(fr.header.description?.endsWith('frozen timestamp.')).toBe(true);
    });

    it('reads `metadata` as the exact JSON string the writer stored', async () => {
        const fr = await FlatRecord.open(readFixture('with-metadata.frb'));
        const meta = JSON.parse(fr.header.metadata!);
        expect(meta.source).toBe('flatrecord/test-fixtures');
        expect(meta.license).toBe('BSD-2-Clause');
        expect(meta.tags).toEqual(['demo', 'metadata', 'roundtrip']);
    });

    it('reads `timestamp` as the pinned millisecond value', async () => {
        const fr = await FlatRecord.open(readFixture('with-metadata.frb'));
        expect(fr.header.timestamp).toBe(1_700_000_000_000);
        // Confirm it round-trips as a proper Date.
        const d = new Date(fr.header.timestamp!);
        expect(d.toISOString()).toBe('2023-11-14T22:13:20.000Z');
    });

    it('content rows still round-trip alongside the metadata', async () => {
        const result = await deserialize(readFixture('with-metadata.frb'));
        if (result.mode !== 'table' && result.mode !== 'graph') throw new Error('expected tabular');
        expect(result.rows).toEqual([
            { id: 'r1', label: 'Alpha' },
            { id: 'r2', label: 'Beta' },
        ]);
    });

    it('declared column index works on a metadata-rich file', async () => {
        const fr = await FlatRecord.open(readFixture('with-metadata.frb'));
        const out: string[] = [];
        for await (const hit of fr.findFeaturesByText('label', 'alpha')) {
            out.push((hit.feature.properties as { id: string }).id);
        }
        expect(out).toEqual(['r1']);
    });

    it('inspect() shows the metadata-rich file is still a table', async () => {
        const fr = await FlatRecord.open(readFixture('with-metadata.frb'));
        const info = fr.inspect();
        expect(info.mode).toBe('table');
        expect(info.featuresCount).toBe(2);
        expect(info.crc32.verified).toBe(true);
    });
});
