# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatGeobuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ColumnIndexEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsColumnIndexEntry(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ColumnIndexEntry()
        x.Init(buf, n + offset)
        return x

    # ColumnIndexEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColumnIndexEntry
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ColumnIndexEntry
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ColumnIndexEntry
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ColumnIndexEntryStart(builder): builder.StartObject(3)
def ColumnIndexEntryAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def ColumnIndexEntryAddOffset(builder, offset): builder.PrependUint64Slot(1, offset, 0)
def ColumnIndexEntryAddLength(builder, length): builder.PrependUint64Slot(2, length, 0)
def ColumnIndexEntryEnd(builder): return builder.EndObject()
